spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sv?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&nullCatalogMeansCurrent=true
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
  thymeleaf:
    cache: false
  jackson:
          date-format: yyyy-MM-dd HH:mm:ss
          time-zone: GMT+8
  servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 100MB
mybatis:
#  type-aliases-package: guet.sgc.sv.entity
  mapper-locations: classpath:mapper/*.xml
#pagehelper配置信息
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  config: classpath:logback.xml
server:
  port: 8080
  servlet:
    context-path: /sv
fileRootPath: http://119.3.216.118:8080/sv